#!/bin/bash

# If a global bashrc exists, source that first
# Usually exists on CentOS systems, etc

[[ -f /etc/bashrc ]] && source /etc/bashrc

if [[ -n "${PS1}" ]]; then
    source ~/.bash_extras
fi
